import type { InboxItem } from "@/domain/types";
import { daysAgoIso, jpDateAhead } from "./helpers";

export const INBOX_ITEMS: InboxItem[] = [
  {
    id: "INBOX-001",
    source: "gmail",
    sender: "佐々木（総務部）",
    senderOrganization: "株式会社サンプル商事",
    subject: "社会保険手続きについてのご相談",
    content: `お世話になっております。株式会社サンプル商事 総務部の佐々木です。

${jpDateAhead(12)}付で正社員として山田太郎さんが入社予定です。健康保険・厚生年金・雇用保険の資格取得手続きをお願いしたく、必要書類を教えていただけますでしょうか。

本人の連絡先は 090-1234-5678、メールは yamada.taro@example.com です。扶養家族はいません。住所は東京都千代田区丸の内1-1-1 サンプルビル5階 です。

よろしくお願いいたします。`,
    receivedAt: daysAgoIso(0, 9, 12),
    aiStatus: "not_processed",
    proposalId: null,
    interactionId: null,
  },
  {
    id: "INBOX-002",
    source: "line_works",
    sender: "中村",
    senderOrganization: "合同会社デモ食品",
    subject: "パート従業員の退職手続き",
    content: `お疲れさまです。パートの田中さんが${jpDateAhead(9)}で退職することになりました。本人から離職票が欲しいと言われています。資格喪失の手続きをお願いします。保険証は最終日に回収予定です。`,
    receivedAt: daysAgoIso(0, 8, 41),
    aiStatus: "not_processed",
    proposalId: null,
    interactionId: null,
  },
  {
    id: "INBOX-003",
    source: "voice_memo",
    sender: "高橋（面談後メモ）",
    senderOrganization: "有限会社テスト建設",
    subject: "面談メモ：建設業許可の新規申請相談",
    content: `有限会社テスト建設の田村社長と面談。建設業許可の新規申請を検討している。専任技術者は2級施工管理技士の資格を持つ社員がいるとのこと。経営業務の管理責任者は田村社長本人で経験は7年ほど。決算書は2期分準備できる。申請希望時期はまだ決まっていないので、あらためて連絡をもらう。`,
    receivedAt: daysAgoIso(0, 17, 5),
    aiStatus: "not_processed",
    proposalId: null,
    interactionId: null,
  },
  {
    id: "INBOX-004",
    source: "phone_memo",
    sender: "小林（人事）",
    senderOrganization: "サンプル物流株式会社",
    subject: "電話メモ：就業規則の変更（フレックスタイム導入）",
    content: `サンプル物流株式会社の小林様より電話。事務部門にフレックスタイム制を導入したいので就業規則の変更をお願いしたい。施行希望日は${jpDateAhead(45)}。従業員は35名。従業員代表の選出はまだ。折り返しは 03-9876-5432 まで。`,
    receivedAt: daysAgoIso(1, 14, 20),
    aiStatus: "not_processed",
    proposalId: null,
    interactionId: null,
  },
  {
    id: "INBOX-005",
    source: "meeting_note",
    sender: "佐藤（所長）",
    senderOrganization: "株式会社モデル設計",
    subject: "面談記録：キャリアアップ助成金の相談",
    content: `株式会社モデル設計 代表の岡田様と初回面談。契約社員2名を来年度に正社員転換したいので、キャリアアップ助成金の活用を検討したい。就業規則に転換制度の規定がない可能性がある。従業員数は12名。次回までに雇用契約書と就業規則を送ってもらう。`,
    receivedAt: daysAgoIso(1, 11, 0),
    aiStatus: "not_processed",
    proposalId: null,
    interactionId: null,
  },
  {
    id: "INBOX-006",
    source: "gmail",
    sender: "佐々木（総務部）",
    senderOrganization: "株式会社サンプル商事",
    subject: "外国籍社員の在留資格更新について",
    content: `お世話になっております。株式会社サンプル商事の佐々木です。技術部のグエン・ヴァン・アンさんの在留資格（技術・人文知識・国際業務）の在留期限が${jpDateAhead(60)}までとなっております。更新申請の手続きをお願いできますでしょうか。必要書類を教えてください。`,
    receivedAt: daysAgoIso(2, 10, 30),
    aiStatus: "review_required",
    proposalId: "PROP-0001",
    interactionId: "INT-0010",
  },
  {
    id: "INBOX-007",
    source: "gmail",
    sender: "セミナー事務局",
    senderOrganization: null,
    subject: "【ご案内】人事労務DXセミナー開催のお知らせ",
    content: `いつもお世話になっております。人事労務DXセミナーを開催いたします。参加無料、オンライン開催です。ご興味がございましたらお申し込みください。`,
    receivedAt: daysAgoIso(3, 9, 0),
    aiStatus: "rejected",
    proposalId: "PROP-0003",
    interactionId: "INT-0011",
  },
  {
    id: "INBOX-008",
    source: "line_works",
    sender: "小林（人事）",
    senderOrganization: "サンプル物流株式会社",
    subject: "先日の件",
    content: `先日はありがとうございました。社内で確認して来週あらためてご連絡します。`,
    receivedAt: daysAgoIso(3, 16, 45),
    aiStatus: "not_processed",
    proposalId: null,
    interactionId: null,
  },
];
