import type { Interaction } from "@/domain/types";
import { daysAgoIso, jpDateAhead } from "./helpers";

export const INTERACTIONS: Interaction[] = [
  { id: "INT-0001", customerId: "CUS-001", caseId: "CASE-0001", type: "email", source: "gmail", subject: "算定基礎届の資料送付", content: "佐々木です。4〜6月の賃金台帳を添付します。ご確認ください。", maskedContent: "[PERSON_001]です。4〜6月の賃金台帳を添付します。ご確認ください。", inboxItemId: null, createdAt: daysAgoIso(58) },
  { id: "INT-0002", customerId: "CUS-001", caseId: "CASE-0001", type: "email", source: "manual", subject: "算定基礎届 提出完了のご連絡", content: "算定基礎届の提出が完了しました。控えを添付します。", maskedContent: "算定基礎届の提出が完了しました。控えを添付します。", inboxItemId: null, createdAt: daysAgoIso(40) },
  { id: "INT-0003", customerId: "CUS-002", caseId: "CASE-0002", type: "meeting", source: "meeting_note", subject: "建設業許可 更新の打合せ", content: "田村社長と打合せ。決算変更届の未提出年度があるかを確認することになった。", maskedContent: "[PERSON_001]社長と打合せ。決算変更届の未提出年度があるかを確認することになった。", inboxItemId: null, createdAt: daysAgoIso(25) },
  { id: "INT-0004", customerId: "CUS-002", caseId: "CASE-0002", type: "phone", source: "phone_memo", subject: "納税証明書の取得について", content: "田村社長へ電話。納税証明書は来週取得予定とのこと。", maskedContent: "[PERSON_001]社長へ電話。納税証明書は来週取得予定とのこと。", inboxItemId: null, createdAt: daysAgoIso(4) },
  { id: "INT-0005", customerId: "CUS-003", caseId: "CASE-0003", type: "line_works", source: "line_works", subject: "36協定の更新について", content: "中村です。36協定の期限が近いので更新をお願いします。", maskedContent: "[PERSON_001]です。36協定の期限が近いので更新をお願いします。", inboxItemId: null, createdAt: daysAgoIso(18) },
  { id: "INT-0006", customerId: "CUS-003", caseId: "CASE-0003", type: "line_works", source: "manual", subject: "労働者代表の選出方法のご案内", content: "労働者代表の選出方法（投票・挙手等）をご案内しました。選出後にご連絡ください。", maskedContent: "労働者代表の選出方法（投票・挙手等）をご案内しました。選出後にご連絡ください。", inboxItemId: null, createdAt: daysAgoIso(12) },
  { id: "INT-0007", customerId: "CUS-004", caseId: "CASE-0004", type: "phone", source: "phone_memo", subject: "有給休暇の年5日取得義務について", content: "小林様より電話。年5日取得の管理方法と管理簿について相談。", maskedContent: "[PERSON_001]様より電話。年5日取得の管理方法と管理簿について相談。", inboxItemId: null, createdAt: daysAgoIso(6) },
  { id: "INT-0008", customerId: "CUS-001", caseId: "CASE-0005", type: "email", source: "gmail", subject: "従業員の扶養追加について", content: "佐々木です。技術部の従業員に子供が生まれたので扶養に追加したいです。出生日は先週です。", maskedContent: "[PERSON_001]です。技術部の従業員に子供が生まれたので扶養に追加したいです。出生日は先週です。", inboxItemId: null, createdAt: daysAgoIso(8) },
  { id: "INT-0009", customerId: "CUS-001", caseId: "CASE-0005", type: "note", source: "manual", subject: "必要書類の案内", content: "出生を証明する書類（住民票）を依頼。受領後に異動届を作成する。", maskedContent: "出生を証明する書類（住民票）を依頼。受領後に異動届を作成する。", inboxItemId: null, createdAt: daysAgoIso(6) },
  { id: "INT-0010", customerId: "CUS-001", caseId: null, type: "email", source: "gmail", subject: "外国籍社員の在留資格更新について", content: `お世話になっております。株式会社サンプル商事の佐々木です。技術部のグエン・ヴァン・アンさんの在留資格（技術・人文知識・国際業務）の在留期限が${jpDateAhead(60)}までとなっております。更新申請の手続きをお願いできますでしょうか。必要書類を教えてください。`, maskedContent: `お世話になっております。[ORG_001]の[PERSON_001]です。技術部の[PERSON_002]さんの在留資格（技術・人文知識・国際業務）の在留期限が${jpDateAhead(60)}までとなっております。更新申請の手続きをお願いできますでしょうか。必要書類を教えてください。`, inboxItemId: "INBOX-006", createdAt: daysAgoIso(2, 10, 31) },
  { id: "INT-0011", customerId: null, caseId: null, type: "email", source: "gmail", subject: "【ご案内】人事労務DXセミナー開催のお知らせ", content: "いつもお世話になっております。人事労務DXセミナーを開催いたします。参加無料、オンライン開催です。", maskedContent: "いつもお世話になっております。人事労務DXセミナーを開催いたします。参加無料、オンライン開催です。", inboxItemId: "INBOX-007", createdAt: daysAgoIso(3, 9, 1) },
  { id: "INT-0012", customerId: "CUS-003", caseId: "CASE-0006", type: "email", source: "gmail", subject: "夏季賞与の支払届について", content: "中村です。夏季賞与を支給するので賞与支払届をお願いします。", maskedContent: "[PERSON_001]です。夏季賞与を支給するので賞与支払届をお願いします。", inboxItemId: null, createdAt: daysAgoIso(1) },
];
