import type { AIProposal, KnowledgeReference } from "@/domain/types";
import { daysAgoDate, daysAgoIso, daysAheadDate } from "./helpers";

type SeedProposal = Omit<AIProposal, "updatedAt">;

export const KNOWLEDGE_REFERENCES: KnowledgeReference[] = [
  { id: "REF-0001", knowledgeDocumentId: "KB-004", query: "扶養 異動届 被扶養者 必要書類", relevance: "high", score: 0.71, usedBy: "PROP-0002", caseId: "CASE-0005", proposalId: "PROP-0002", createdAt: daysAgoIso(8) },
  { id: "REF-0002", knowledgeDocumentId: "KB-009", query: "扶養 異動届 被扶養者 必要書類", relevance: "medium", score: 0.31, usedBy: "PROP-0002", caseId: "CASE-0005", proposalId: "PROP-0002", createdAt: daysAgoIso(8) },
  { id: "REF-0003", knowledgeDocumentId: "KB-011", query: "在留資格 変更 就労 必要書類 入管", relevance: "high", score: 0.68, usedBy: "PROP-0001", caseId: null, proposalId: "PROP-0001", createdAt: daysAgoIso(2, 10, 32) },
  { id: "REF-0004", knowledgeDocumentId: "KB-014", query: "在留資格 変更 就労 必要書類 入管", relevance: "low", score: 0.14, usedBy: "PROP-0001", caseId: null, proposalId: "PROP-0001", createdAt: daysAgoIso(2, 10, 32) },
  { id: "REF-0005", knowledgeDocumentId: "KB-010", query: "建設業許可 更新 必要書類", relevance: "high", score: 0.66, usedBy: "assistant", caseId: "CASE-0002", proposalId: null, createdAt: daysAgoIso(20) },
  { id: "REF-0006", knowledgeDocumentId: "KB-015", query: "建設業許可 更新 必要書類", relevance: "medium", score: 0.36, usedBy: "assistant", caseId: "CASE-0002", proposalId: null, createdAt: daysAgoIso(20) },
  { id: "REF-0007", knowledgeDocumentId: "KB-008", query: "有給休暇 年5日 取得義務", relevance: "high", score: 0.74, usedBy: "assistant", caseId: "CASE-0004", proposalId: null, createdAt: daysAgoIso(5) },
];

export const PROPOSALS: SeedProposal[] = [
  {
    id: "PROP-0001",
    sourceInteractionId: "INT-0010",
    inboxItemId: "INBOX-006",
    customer: { customerId: "CUS-001", maskedName: "[ORG_001]", matchedOrganization: "株式会社サンプル商事", isNew: false },
    intent: "immigration",
    intentLabel: "在留資格 申請・変更",
    summary: `[ORG_001] から 在留資格 申請・変更 に関する依頼。対象者 1 名（[PERSON_002]）。在留期限: ${daysAheadDate(60)} 参照ナレッジ: 在留資格_就労ビザ変更手続き.md`,
    caseProposal: { title: "[ORG_001] 在留資格 変更・更新申請", description: `外国人雇用に伴う在留資格の変更・更新申請。\n在留期限: ${daysAheadDate(60)}\n参照ナレッジ: 在留資格_就労ビザ変更手続き.md`, priority: "high", dueDate: daysAheadDate(46), assignee: "高橋" },
    taskProposals: [
      { title: "在留カード・パスポート・雇用契約内容の確認", description: "現在の在留資格と業務内容の適合性を確認する。", priority: "high", dueDate: daysAheadDate(1), assignee: "高橋" },
      { title: "申請書類の作成", description: "在留期間更新許可申請書と理由書を作成する。", priority: "high", dueDate: daysAheadDate(39), assignee: "高橋" },
      { title: "入管への申請", description: "オンラインまたは窓口で申請し受付票を保管する。", priority: "high", dueDate: daysAheadDate(46), assignee: "高橋" },
    ],
    missingInformation: [],
    confidence: "high",
    knowledgeReferenceIds: ["REF-0003", "REF-0004"],
    status: "pending_review",
    reviewNote: null,
    reviewedBy: null,
    reviewedAt: null,
    createdCaseId: null,
    processingMs: 2140,
    createdAt: daysAgoIso(2, 10, 33),
  },
  {
    id: "PROP-0002",
    sourceInteractionId: "INT-0008",
    inboxItemId: null,
    customer: { customerId: "CUS-001", maskedName: "[ORG_001]", matchedOrganization: "株式会社サンプル商事", isNew: false },
    intent: "dependent_change",
    intentLabel: "被扶養者 異動手続き",
    summary: `[ORG_001] から 被扶養者 異動手続き に関する依頼。異動日（事実発生日）: ${daysAgoDate(7)} 参照ナレッジ: 被扶養者異動届の取り扱い.md、FAQ_社会保険の加入条件.md`,
    caseProposal: { title: "[ORG_001] 被扶養者異動届", description: "被扶養者の追加・削除に伴う異動届の作成と提出。", priority: "medium", dueDate: daysAgoDate(2), assignee: "鈴木" },
    taskProposals: [
      { title: "異動事由と必要書類の確認", description: "続柄・収入要件・同居要件を確認し必要書類を案内する。", priority: "medium", dueDate: daysAgoDate(6), assignee: "鈴木" },
      { title: "被扶養者異動届の作成・提出", description: "届出書を作成し提出する。", priority: "medium", dueDate: daysAgoDate(2), assignee: "鈴木" },
    ],
    missingInformation: [],
    confidence: "high",
    knowledgeReferenceIds: ["REF-0001", "REF-0002"],
    status: "approved",
    reviewNote: "内容確認済み。異動日を住民票で再確認すること。",
    reviewedBy: "佐藤（所長）",
    reviewedAt: daysAgoIso(8, 11, 5),
    createdCaseId: "CASE-0005",
    processingMs: 1880,
    createdAt: daysAgoIso(8, 10, 20),
  },
  {
    id: "PROP-0003",
    sourceInteractionId: "INT-0011",
    inboxItemId: "INBOX-007",
    customer: { customerId: null, maskedName: "[ORG_NEW]", matchedOrganization: null, isNew: true },
    intent: "other",
    intentLabel: "その他・分類不能",
    summary: "[ORG_NEW] から その他・分類不能 に関する依頼。 参照ナレッジなし",
    caseProposal: { title: "[ORG_NEW] 問い合わせ対応", description: "分類できなかった依頼。担当者による内容確認が必要。", priority: "low", dueDate: daysAgoDate(-4), assignee: "鈴木" },
    taskProposals: [{ title: "依頼内容の確認と分類", description: "AI が分類できなかったため担当者が内容を確認する。", priority: "medium", dueDate: daysAgoDate(0), assignee: "鈴木" }],
    missingInformation: [{ field: "knowledge", label: "参照ナレッジ", message: "関連する確認済みナレッジが見つかりませんでした。担当者が根拠を確認してください。", severity: "recommended" }],
    confidence: "low",
    knowledgeReferenceIds: [],
    status: "rejected",
    reviewNote: "営業メールのため案件化不要。",
    reviewedBy: "佐藤（所長）",
    reviewedAt: daysAgoIso(3, 9, 40),
    createdCaseId: null,
    processingMs: 1520,
    createdAt: daysAgoIso(3, 9, 2),
  },
];
